#!/bin/bash

# Script base que apenas insere e remove caracteres U+2000 (Unicode) no módulo, a fim de dar espaço para a traybar, que já pode ter um offset inicial configurado, a depender da intenção da rice/pessoa.
# EN: base script which just insert and remove U+2000 (Unicode) characters in the module, giving the needed offset for traybar, that may need some initial offset setted up, depending on ricing/people intentions.

# Daltro Augusto. 2021-. LGPLv2.1.

! [ -f "$HOME/.config/.trayoffset" ] && touch "$HOME/.config/.trayoffset"

POLYBAR_TRAYOFFSET=$(<"${HOME}/.config/.trayoffset")
SYNTAX_TEXT="SYNTAX: [ \e[3madd [no. of spaces]\e[0m | \e[3mecho\e[0m | \e[3mremove\e[0m | \e[3mremove-all\e[0m ]"

case $1 in
	add)
		result="${POLYBAR_TRAYOFFSET}      "

		if test -n "$2" -a "$2" -ge 1 2>/dev/null ; then
			result="${POLYBAR_TRAYOFFSET}"

			for((i=0; i<$2; i++)); do
				result+=" "
			done
		fi

		echo "$result" > "${HOME}/.config/.trayoffset"
	;;

	echo)
		echo "${POLYBAR_TRAYOFFSET}"
	;;

	remove)
		i=${POLYBAR_TRAYOFFSET}
		offset=$((${#i} - 6))

		if test -n "$2" -a "$2" -ge 1 2>/dev/null; then offset=$((${#i} - $2)); fi

		result=${i:0:$offset}
		
		echo "$result" > "${HOME}/.config/.trayoffset"
	;;

	remove-all)
		echo "" > "${HOME}/.config/.trayoffset"
	;;

	*)
		echo -e "$SYNTAX_TEXT"
	;;
esac
